# Generated by Django 5.2.7 on 2025-11-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('party', models.CharField(blank=True, max_length=100)),
                ('office', models.CharField(max_length=255)),
                ('election_name', models.CharField(blank=True, max_length=255)),
                ('election_type', models.CharField(blank=True, max_length=100)),
                ('election_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default='US', max_length=2)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('vote_percent', models.FloatField(blank=True, null=True)),
                ('candidate_url', models.URLField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('race_id', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='civicapi', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-election_date', 'name'],
                'indexes': [models.Index(fields=['name'], name='civicapi_ca_name_b2981c_idx'), models.Index(fields=['state', 'office'], name='civicapi_ca_state_9a96fe_idx'), models.Index(fields=['election_date'], name='civicapi_ca_electio_c654b0_idx')],
                'unique_together': {('name', 'race_id')},
            },
        ),
    ]
