# Generated by Django 5.2.7 on 2025-11-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicapi', '0003_remove_user_password_user_name_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
