# Generated by Django 5.2.7 on 2025-11-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicapi', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('race_type', models.CharField(blank=True, max_length=100)),
                ('election_type', models.CharField(blank=True, max_length=100)),
                ('election_date', models.DateField()),
                ('country', models.CharField(default='US', max_length=3)),
                ('province', models.CharField(blank=True, max_length=5)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-election_date', 'name'],
                'indexes': [models.Index(fields=['election_date', 'country', 'province'], name='civicapi_el_electio_54d32e_idx'), models.Index(fields=['country', 'province'], name='civicapi_el_country_8e01bd_idx')],
            },
        ),
    ]
